In [8]:
import pandas as pd 
import numpy as np
import json
from helpers import *

In [9]:
path_hdro2019 = "C:/Users/joach/code-projects/WaterSecurity/data/unlabeled/hdro2019.json"
export_path = "preprocessed_data/preprocessed_hdro19.csv"

In [10]:
with open(path_hdro2019) as jsonfile:
    json_hdro = json.load(jsonfile)

In [11]:
inicator_values = json_hdro['indicator_value']
country_name = json_hdro['country_name']
indicator_name = json_hdro['indicator_name']

In [12]:
df_inicator_values = pd.DataFrame(inicator_values).T
df_inicator_values.columns = [indicator_name[nm] for nm in df_inicator_values.columns]
df_inicator_values = df_inicator_values.applymap(lambda x: x['2019'] if pd.notnull(x) else x)
dropColumnHalf(df_inicator_values)
df_inicator_values

,Population with at least some secondary education (% ages 25 and older),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)","Mean years of schooling, female (years)","Mean years of schooling, male (years)",Share of seats in parliament (% held by women),"Adolescent birth rate (births per 1,000 women ages 15-19)",Vulnerable employment (% of total employment),Total population (millions),Urban population (%),...,Gender Development Index (GDI),"Estimated gross national income per capita, female (2017 PPP $)","Estimated gross national income per capita, male (2017 PPP $)","Human Development Index (HDI), female","Human Development Index (HDI), male",Inequality-adjusted income index,Overall loss in HDI due to inequality (%),Inequality in income (%),Coefficient of human inequality,Inequality-adjusted HDI (IHDI)
AFG,26.080,13.220,36.920,1.948,6.006,27.244,68.957,79.726,38.042,25.8,...,0.659,819.385,3565.865,0.391,0.593,NaN,NaN,NaN,NaN,NaN
AGO,30.232,23.133,38.056,4.023,6.359,30.000,150.526,65.995,31.825,66.2,...,0.903,5205.049,7022.231,0.552,0.611,0.442,31.670,28.900,31.733,0.397
ALB,93.174,93.700,92.497,9.702,10.614,29.508,19.642,52.852,2.881,61.2,...,0.967,11004.455,16884.667,0.780,0.807,0.648,10.943,13.179,10.893,0.708
AND,72.327,71.484,73.327,10.439,10.564,46.429,NaN,NaN,0.077,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARG,57.158,59.161,54.828,11.123,10.729,39.877,62.782,21.805,44.781,92.0,...,0.993,14872.167,27825.757,0.835,0.840,0.606,13.728,25.159,13.238,0.729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WSM,74.942,79.127,71.583,NaN,NaN,10.000,23.886,29.983,0.197,18.1,...,NaN,4054.375,8410.109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YEM,28.020,19.920,36.918,2.880,5.146,0.971,60.352,45.627,29.162,37.3,...,0.488,186.041,2980.035,0.270,0.553,0.327,31.702,21.800,30.867,0.321
ZAF,75.478,74.977,78.207,10.031,10.291,45.333,67.908,10.298,58.558,66.9,...,0.986,9247.751,15094.546,0.702,0.712,0.312,33.992,56.996,31.163,0.468
ZMB,44.440,38.488,54.068,6.283,8.176,17.964,120.112,78.134,17.861,44.1,...,0.958,3379.549,3270.422,0.569,0.593,0.292,31.336,44.840,30.592,0.401
ZWE,64.935,59.792,70.783,8.066,8.923,34.571,86.135,64.739,14.645,32.2,...,0.931,2374.612,2984.896,0.550,0.590,0.353,22.767,28.769,22.525,0.441

In [13]:
df_inicator_values.describe()

,Population with at least some secondary education (% ages 25 and older),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)","Mean years of schooling, female (years)","Mean years of schooling, male (years)",Share of seats in parliament (% held by women),"Adolescent birth rate (births per 1,000 women ages 15-19)",Vulnerable employment (% of total employment),Total population (millions),Urban population (%),...,Gender Development Index (GDI),"Estimated gross national income per capita, female (2017 PPP $)","Estimated gross national income per capita, male (2017 PPP $)","Human Development Index (HDI), female","Human Development Index (HDI), male",Inequality-adjusted income index,Overall loss in HDI due to inequality (%),Inequality in income (%),Coefficient of human inequality,Inequality-adjusted HDI (IHDI)
count,175.000000,167.000000,167.000000,174.000000,174.000000,193.000000,185.000000,180.000000,195.000000,195.000000,...,167.000000,178.000000,178.000000,167.000000,167.000000,156.000000,152.000000,156.000000,152.000000,152.000000
mean,61.068074,61.736012,65.823587,8.480017,9.133402,22.981295,48.309346,38.258011,39.391426,59.257436,...,0.938994,14440.998511,24458.331354,0.702683,0.742186,0.545064,19.389145,23.401385,19.002599,0.595250
std,29.610798,29.284050,26.395358,3.421332,2.802984,11.828784,40.528834,27.774415,146.485855,23.231038,...,0.074559,15359.935986,23943.482628,0.165867,0.143194,0.172789,9.948718,9.744004,9.777324,0.190002
min,0.000000,1.738000,9.000000,1.070000,2.256000,0.100000,0.283000,0.144000,0.011000,13.200000,...,0.488000,186.041000,640.105000,0.270000,0.432000,0.176000,4.444000,8.500000,4.424000,0.232000
25%,37.296500,36.925000,45.356500,5.850000,6.733750,14.765000,13.177000,12.538250,2.081000,41.200000,...,0.908500,2925.614250,6275.933750,0.577000,0.621500,0.404750,10.792250,16.603000,10.594000,0.431500
50%,64.828000,68.067000,70.682000,9.111000,9.252500,21.094000,40.536000,32.533500,8.772000,60.000000,...,0.965000,8399.442500,16951.357000,0.730000,0.760000,0.527500,17.934500,21.779500,17.526000,0.604000
75%,89.145000,87.990500,90.916500,11.230500,11.551000,30.000000,70.504000,63.345500,28.562500,78.000000,...,0.986000,22583.779500,35488.476000,0.831500,0.848500,0.691750,27.615250,28.625000,27.012500,0.767250
max,100.000000,100.000000,100.000000,13.882000,14.431000,55.660000,186.538000,94.581000,1433.784000,100.000000,...,1.036000,71387.276000,107833.029000,0.949000,0.965000,0.858000,45.307000,56.996000,44.167000,0.899000

In [14]:
df_inicator_values.to_csv(export_path)